
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop1?serverTimezone=Hongkong&allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 823360
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8085
